# kubesphere configuration

server:
  http:
    hostname: localhost
    port: 8000
    static:
      development:
        /public: server/public
        /assets: src/assets
        /build: build
        /dist: dist
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist

  # redis config for multi replicas
  # redis:
  #   port: 6379
  #   host: 127.0.0.1
  redisTimeout: 5000

  # kubesphere console session params, not login session
  sessionKey: 'kubesphere:sess'
  sessionTimeout: 7200000 # unit: millisecond

  # backend service gateway server
  apiServer:
    # url: http://localhost:8090
    # wsUrl: ws://localhost:8090
    url: http://10.248.225.17:30882
    wsUrl: ws://10.248.225.17:30882
    # url: http://ks-apiserver.kubesphere-system.svc
    # wsUrl: ws://ks-apiserver.kubesphere-system.svc

  #backend server Sailor server
  sailorServer:
    # url: http://sailor
    # wsUrl: ws://sailor
    url: http://127.0.0.1:8888
    wsUrl: ws://127.0.0.1:8888

  # docker image search default url
  dockerHubUrl: https://hub.docker.com

client:
  title: KubeSphere
  description: ''

  version:
    kubesphere: 3.0.0

  # kubesphere urls
  issueUrl: https://github.com/kubesphere/kubesphere/issues/new/choose
  reposUrl: https://github.com/kubesphere/kubesphere
  slackUrl: https://kubesphere.slack.com
  documents:
    url: https://kubesphere.io/docs
    api: https://kubesphere.io/docs/v2.1/zh-CN/api-reference/api-docs/
    version: v2.1

  # current support lanaguages
  supportLangs:
    - label: '繁體中文'
      value: 'tc'
    - label: '简体中文'
      value: 'zh'
    - label: 'English'
      value: 'en'
  defaultLang: 'en'

  # platform management navigations
  globalNavs:
    - name: clusters
      title: Clusters Management
      desc: CLUSTERS_MANAGE_DESC
      icon: cluster
    - name: access
      title: Access Control
      icon: key
      authKey: users|roles|workspaces
    - name: apps-manage
      title: App Store Management
      icon: openpitrix
      authKey: app-templates
      authAction: manage
      ksModule: openpitrix
    - name: settings
      title: Platform Settings
      icon: cogwheel
      authKey: platform-settings
      authAction: manage

  clusterNavs:
    - cate: cluster
      items:
        - name: overview
          title: Overview
          icon: dashboard
          skipAuth: true
          showInDisable: true
        - name: nodes
          title: Nodes Management
          icon: nodes
          children:
            - { name: nodes, title: Cluster Nodes }
        - { name: components, title: Service Components, icon: components }
        - { name: projects, title: NAV_PROJECTS, icon: project }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
                - { name: daemonsets, title: DaemonSets }
            - name: jobs
              title: Jobs
              tabs:
                - { name: jobs, title: Jobs }
                - { name: cronjobs, title: CronJobs }
            - { name: pods, title: Pods }
            - { name: services, title: Services }
            - { name: ingresses, title: Routes }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
        - name: network
          title: Network Management
          icon: earth
          children:
            - {
                name: networkpolicies,
                title: Network Policies,
                clusterModule: network,
              }
        # Contains dangerous operations, only available for platform-admin.
        - {
            name: customresources,
            title: Custom Resources,
            icon: select,
            admin: true,
          }
        - name: storage
          title: Storage Management
          icon: database
          children:
            - { name: volumes, title: Volumes }
            - { name: volume-snapshots, title: Snapshots }
            - { name: storageclasses, title: Storage Classes }
        - name: monitoring-alerting
          title: Monitoring & Alerting
          icon: monitor
          children:
            - {
                name: monitor-cluster,
                title: Cluster Status,
                icon: linechart,
                authKey: monitoring,
              }
            - {
                name: monitor-resource,
                title: Application Resources,
                icon: linechart,
                authKey: monitoring,
              }
            - {
                name: alert-messages,
                title: Alerting Messages,
                icon: loudspeaker,
                clusterModule: 'alerting',
              }
            - {
                name: alert-policies,
                title: Alerting Policies,
                icon: hammer,
                clusterModule: 'alerting',
              }
        - name: cluster-settings
          title: Cluster Settings
          icon: cogwheel
          showInDisable: true
          children:
            - {
                name: base-info,
                title: Basic Info,
                skipAuth: true,
                showInDisable: true,
              }
            - {
                name: visibility,
                title: Cluster Visibility,
                authKey: 'cluster-settings',
                multiCluster: true,
              }
            # - { name: members, title: Cluster Members }
            # - { name: roles, title: Cluster Roles }
            - {
                name: mail-server,
                title: Mail Server,
                icon: mail,
                authKey: alerting,
                clusterModule: alerting,
              }
            - {
                name: log-collections,
                title: Log Collections,
                icon: file,
                authKey: logging|events|auditing,
                clusterModule: logging,
              }

  # access control page navigations
  accessNavs:
    - cate: 'access'
      items:
        - { name: workspaces, title: Workspaces, icon: enterprise }
        - { name: accounts, title: NAV_ACCOUNTS, icon: human, authKey: users }
        - { name: roles, title: Account Roles, icon: role }

  # platform settings navigations
  platformSettingsNavs:
    - cate: 'platformsettings'
      items:
        - { name: base-info, title: Platform Info, icon: home, authKey: platform-settings}
        # - { name: cluster, title: '添加集群', icon: cluster, authKey: platform-settings}
        # - { name: node, title: '添加节点', icon: nodes, authKey: platform-settings}
        - { name: racckcommon, title: '机柜网络', icon: hammer, authKey: platform-settings}
        - { name: podcommon, title: '容器网络', icon: pod, authKey: platform-settings}        

  # workspace page navigations
  workspaceNavs:
    - cate: 'workspace'
      items:
        - { name: overview, title: Overview, icon: dashboard, skipAuth: true }
        - name: projects
          title: NAV_PROJECTS
          icon: project
          tabs:
            - { name: projects, title: Projects }
            - { name: federatedprojects, title: Multi-cluster Projects }
        - {
            name: devops,
            title: DevOps Projects,
            icon: strategy-group,
            ksModule: devops,
          }
        - name: apps
          title: Apps Management
          icon: appcenter
          children:
            - {
                name: apps,
                title: App Templates,
                icon: appcenter,
                authKey: app-templates,
                ksModule: openpitrix,
              }
            - {
                name: repos,
                title: App Repos,
                authKey: 'app-repos',
                ksModule: openpitrix,
              }
        - name: management
          title: Workspace Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - { name: roles, title: Workspace Roles }
            - { name: members, title: Workspace Members }

  # apps manage page navigations
  manageAppNavs:
    - cate: 'apps'
      items:
        - { name: store, title: App Store, icon: appcenter }
        - { name: categories, title: App Categories, icon: tag }
        - { name: reviews, title: App Review, icon: safe-notice }

  # project page navigations
  projectNavs:
    - cate: 'project'
      items:
        - { name: overview, title: Overview, icon: dashboard, skipAuth: true }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - { name: applications, title: Applications, icon: application }
            - { name: services, title: Services }
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
                - { name: daemonsets, title: DaemonSets }
            - name: jobs
              title: Jobs
              tabs:
                - { name: jobs, title: Jobs }
                - { name: cronjobs, title: CronJobs }
            - { name: ingresses, title: Routes }
            - { name: pods, title: Pods }
        - name: storage
          title: Storage Management
          icon: database
          children:
            - { name: volumes, title: Volumes }
            - { name: volume-snapshots, title: Snapshots }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
        - {
            name: grayrelease,
            title: Grayscale Release,
            icon: bird,
            authKey: applications,
            clusterModule: servicemesh,
          }
        - {
            name: s2ibuilders,
            title: Image Builder,
            icon: vnas,
            clusterModule: devops,
          }
        - name: monitoring
          title: Monitoring & Alerting
          icon: monitor
          children:
            - {
                name: alert-messages,
                title: Alerting Message,
                authKey: alerting,
                clusterModule: alerting,
              }
            - {
                name: alert-policies,
                title: Alerting Policy,
                authKey: alerting,
                clusterModule: alerting,
              }
            - { name: custom-monitoring, title: Custom Monitoring }
        - name: settings
          title: Project Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - { name: networkpolicies, title: Network Isolation, clusterModule: network, }
            - { name: roles, title: Project Roles }
            - { name: members, title: Project Members }
            - {
                name: advanced,
                title: Advanced Settings,
                authKey: 'project-settings',
              }

  federatedProjectNavs:
    - cate: 'project'
      items:
        - { name: overview, title: Overview, icon: dashboard, skipAuth: true }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - { name: applications, title: Applications, icon: application }
            - { name: services, title: Services }
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
            - { name: ingresses, title: Routes }
        - { name: volumes, title: Volumes, icon: storage }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
        - name: settings
          title: Project Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - {
                name: quota,
                title: Quota Management,
                authKey: 'project-settings',
              }
            - {
                name: advanced,
                title: Advanced Settings,
                authKey: 'project-settings',
              }

  # devops page navigations
  devopsNavs:
    - cate: ''
      items:
        - { name: pipelines, title: Pipelines, icon: application }
        - name: management
          title: DEVOPS_PROJECT_MANAGEMENT
          icon: cogwheel
          open: true
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - { name: credentials, title: Credentials }
            - { name: roles, title: DEVOPS_PROJECT_ROLES }
            - { name: members, title: DEVOPS_PROJECT_MEMBERS }

  # system workspace rules control
  systemWorkspace: system-workspace1
  systemWorkspaceRules:
    devops: []
    members: [view, create, edit, delete]
    projects: [view, edit]
    roles: [view]
    workspaces: [view, edit]
  systemWorkspaceProjectRules:
    alerting: [view, create, edit, delete]
    members: [view, create, edit, delete]
    roles: [view, create, edit, delete]

  # preset infos
  presetUsers: [admin, sonarqube]
  presetGlobalRoles: [platform-admin, platform-regular, workspaces-manager, users-manager]
  presetClusterRoles: [cluster-admin, cluster-viewer]
  presetWorkspaceRoles: [admin, regular, viewer, self-provisioner]
  presetDevOpsRoles: [admin, operator, viewer]
  presetRoles: [admin, operator, viewer]

  # system annotations that need to be hidden for edit
  preservedAnnotations: ['.*kubesphere.io/', 'openpitrix_runtime']

  # namespaces that need to be disable collection file log
  disabledLoggingSidecarNamespace: ['kubesphere-logging-system']

  # loadbalancer annotations, default support qingcloud lb
  loadBalancerDefaultAnnotations:
    service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids: ''
    service.beta.kubernetes.io/qingcloud-load-balancer-type: '0'

  # control error notify on page
  enableErrorNotify: true

  # enable image search when add image for a container
  enableImageSearch: true

  # development
  # disable authorization check when developing
  disableAuthorization: true

  # show kubeconfig
  enableKubeConfig: true

  # show kubeconfig
  defaultNetworkIsolation: false

  # third party tools
  thirdPartyTools:
    []
    # - title:
    #   description:
    #   link:

  # docs url for resources
  resourceDocs:
    applications: /application/app-template/
    composingapps: /application/composing-svc/
    deployments: /workload/deployments/
    statefulsets: /workload/statefulsets/
    daemonsets: /workload/daemonsets/
    jobs: /workload/jobs/
    cronjobs: /workload/cronjobs/
    volumes: /storage/volume/
    storageclasses: /infrastructure/storageclass/
    services: /ingress-service/services/
    grayrelease: /ingress-service/grayscale/
    ingresses: /ingress-service/ingress/
    secrets: /configuration/secrets/
    imageregistry: /configuration/image-registry/
    configmaps: /configuration/configmaps/
    internet: /project-setting/project-gateway/
    nodes: /infrastructure/nodes/
    cicds: /devops/pipeline/
    cridentials: /devops/credential/
    project_base_info: /project-setting/project-quota/
    project_roles: /project-setting/project-roles/
    project_members: /project-setting/project-members/
    s2i_template: /workload/s2i-template/
    helm_specification: /developer/helm-specification/
    helm_developer_guide: /developer/helm-developer-guide/
    custom_console: /developer/custom_console/
  # devops:
  #  replace sonarqube link to customize url origin, default is useless
  # sonarqubeURL: http://139.123.123.123:8080
